// Generated by Claude Opus 4.6
// 2026-04-13
// (Prompted by Braden Vanderwoerd)
// Documented by Claude Opus 4.6 - 2026-04-14
// Generic 16-entry, 64-bit wide synchronous FIFO
// Used for both the command buffer and the data buffer in the graphics pipeline.
// Head/tail pointers wrap naturally via 4-bit overflow to form a circular buffer.

module fifo (
    input  logic        clk,
    input  logic        reset_n,

    input  logic [63:0] data_in,
    input  logic        write_en,
    output logic [63:0] data_out,
    input  logic        read_en,
    output logic        empty,
    output logic [4:0]  count,
    output logic        full
);

    logic [63:0] fifo_mem [0:15]; // 16-entry storage array
    logic [3:0]  head, tail;     // Read and write pointers (wrap via 4-bit overflow)

    always_ff @(posedge clk) begin
        if (!reset_n) begin
            head  <= 4'b0000;
            tail  <= 4'b0000;
            count <= 5'b00000;
        end else begin
            if (write_en && !full && read_en && !empty) begin
                // Simultaneous read + write: pointers advance, count unchanged
                fifo_mem[tail] <= data_in;
                tail  <= tail + 1;
                head  <= head + 1;
            end else if (write_en && !full) begin
                fifo_mem[tail] <= data_in;
                tail  <= tail + 1;
                count <= count + 1;
            end else if (read_en && !empty) begin
                head  <= head + 1;
                count <= count - 1;
            end
        end
    end

    assign data_out = fifo_mem[head]; // Combinational read from head

    assign empty = (count == 0);
    assign full  = (count == 16);

endmodule