// Generated by Claude Opus 4.6
// 2026-04-13
// (Prompted by Braden Vanderwoerd)
// Documented by Claude Opus 4.6 - 2026-04-14
// config.h — Project-wide constants for the GPU software.
// Screen dimensions match the hardware frame buffer; color ranges match the 6-bit pixel format.

#ifndef CONFIG_H
#define CONFIG_H

// Framebuffer dimensions.
#define SCREEN_W 320
#define SCREEN_H 240

// RGB565: red 5 bits, green 6 bits, blue 5 bits.
#define R_MAX 31
#define G_MAX 63
#define B_MAX 31

#endif