// Generated by Claude Opus 4.6
// 2026-04-13
// (Prompted by Braden Vanderwoerd)
// Documented by Claude Opus 4.6 - 2026-04-14
// demos.h — Visual demo function declarations.
// Each demo_* function is a self-contained animation that runs until the user presses a key.

#ifndef DEMOS_H
#define DEMOS_H

void demo_full(void);
void playground(void);
void demo_spinning_cube(void);
void demo_dvd_bounce(void);
void demo_game_of_life(void);
void demo_spinning_triangles(void);

#endif